baseURL = "https://gesucca-official.github.io/"
languageCode = "en-us"
paginate = 8
theme = "portio"
title = "Simone Cipriani"

# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Software"
url = "#portfolio"
weight = 3
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 4
[[menu.main]]
name = "Music"
url = "#service"
weight = 5
[[menu.main]]
name = "Writings"
url = "#blog"
weight = 6
[[menu.main]]
name = "Others"
url = "#skills"
weight = 7
[[menu.main]]
name = "Contacts"
url = "#contact"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Software"
url = "#portfolio"
weight = 2
[[menu.sitemap]]
name = "Resume"
url = "#resume"
weight = 3
[[menu.sitemap]]
name = "Music"
url = "#service"
weight = 4
[[menu.sitemap]]
name = "Writings"
url = "#blog"
weight = 5
[[menu.sitemap]]
name = "Other Skills"
url = "#skills"
weight = 6
[[menu.sitemap]]
name = "Contacts"
url = "#contact"
weight = 7

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Simone Cipriani 2025"
footerLogo = "images/contact/widget-logo.png"
# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/JpTXRUa"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Viale Galileo Galilei, Prato, ITALY"
email = "simone.cipriani.it@gmail.com"
openingHours = "Monday to Friday - 9:00 to 18:00"
phone = "Ask for phone number over email."

# Social icons
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/gesucca/"
weight = 1

[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/simone-cipriani-ba313a205/"
weight = 2
